name = "classtable-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
SOURCE_BASE_URL = "http://class.ckgsh.ntpc.edu.tw/classtable"

[[d1_databases]]
binding = "DB"
database_name = "classtable-db"
database_id = "920c2c69-614f-41c3-be2e-a0a95fdf2a69"

[triggers]
crons = ["30 21 * * *"]
